export const EMPLOYEE_FETCH_ITEMS = "EMPLOYEE_FETCH_ITEMS";
export const EMPLOYEE_ADD_ITEM = "EMPLOYEE_ADD_ITEM";
export const EMPLOYEE_UPDATE_ITEM = "EMPLOYEE_UPDATE_ITEM";
export const EMPLOYEE_DELETE_ITEM = "EMPLOYEE_DELETE_ITEM";
